version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "02:00"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "02:00"
