project:
  proj_dir: project/20230301_193838
  model_dir: project/20230301_193838/models/
  cfg_fname: config.yml
  train_log:
    path: project/20230301_193838/train.log
    screen_intvl: 200
    headers: {Loss: ':3.4f', bkb_grad: ':3.2f', head_grad: ':3.2f', Mag_mean: ':3.2f',
      Mag_std: ':3.2f'}
  val_log:
    path: project/20230301_193838/val.log
    screen_intvl: 1
    headers: {LFW: ':3.3f', AgeDB-30: ':3.3f', CA-LFW: ':3.3f', CP-LFW: ':3.3f'}
  val_intvl: 2000
  save_iters: [2000, 4000, 6000, 8000, 10000]
data:
  train:
    dataset: {type: ClassDataset, data_dir: /home/tham/Desktop/KH/opensphere/customize/QMUL-SurvFace,
      test_mode: false, name: VGGFace2, ann_path: /home/tham/Desktop/KH/opensphere/customize/QMUL-SurvFace/SurvFace_train_ann.txt}
    dataloader: {type: DataLoader, batch_size: 512, shuffle: true, drop_last: true,
      num_workers: 4, pin_memory: true}
  val:
  - dataset:
      type: PairDataset
      data_dir: data/val/
      test_mode: true
      name: LFW
      ann_path: data/val/lfw_ann.txt
      metrics: [ACC]
    dataloader: {type: DataLoader, batch_size: 64, shuffle: false, drop_last: false,
      num_workers: 4, pin_memory: true}
  - dataset:
      type: PairDataset
      data_dir: data/val/
      test_mode: true
      name: AgeDB-30
      ann_path: data/val/agedb_30_ann.txt
      metrics: [ACC]
    dataloader: {type: DataLoader, batch_size: 64, shuffle: false, drop_last: false,
      num_workers: 4, pin_memory: true}
  - dataset:
      type: PairDataset
      data_dir: data/val/
      test_mode: true
      name: CA-LFW
      ann_path: data/val/calfw_ann.txt
      metrics: [ACC]
    dataloader: {type: DataLoader, batch_size: 64, shuffle: false, drop_last: false,
      num_workers: 4, pin_memory: true}
  - dataset:
      type: PairDataset
      data_dir: data/val/
      test_mode: true
      name: CP-LFW
      ann_path: data/val/cplfw_ann.txt
      metrics: [ACC]
    dataloader: {type: DataLoader, batch_size: 64, shuffle: false, drop_last: false,
      num_workers: 4, pin_memory: true}
parallel: {backend: nccl, dist_url: 'tcp://127.0.0.1:21119', device_ids: '0', world_size: 1}
model:
  backbone:
    net:
      type: sfnet20_deprecated
      in_channel: 3
      channels: [64, 128, 256, 512]
      out_channel: 512
    optimizer: {type: SGD, lr: 0.1, momentum: 0.9, weight_decay: 0.0005}
    scheduler:
      type: MultiStepLR
      milestones: [5000, 7800, 9400, 10000]
      gamma: 0.1
    clip_grad_norm: 100000.0
  head:
    net: {type: SphereFace, s: 32, m: 1.7, feat_dim: 512, num_class: 5319}
    optimizer: {type: SGD, lr: 0.1, momentum: 0.9, weight_decay: 0.0005}
    scheduler:
      type: MultiStepLR
      milestones: [5000, 7800, 9400, 10000]
      gamma: 0.1
    clip_grad_norm: 100000.0
